# Generated by Django 4.0.5 on 2022-06-23 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="user_followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
